# -*- coding: utf-8 -*-
"""week1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HBJxGHtNd8R3eZvfTMSC139yQ8bHrFoX
"""

num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))
operator = input("Enter operator (+, -, *, /): ")

if operator == "+":
    print("Result:", num1 + num2)
elif operator == "-":
    print("Result:", num1 - num2)
elif operator == "*":
    print("Result:", num1 * num2)
elif operator == "/":
    if num2 != 0:
        print("Result:", num1 / num2)
    else:
        print("Division by zero is not allowed.")
else:
    print("Invalid operator")

choice = input("Convert (C)elsius to Fahrenheit or (F)ahrenheit to Celsius? ")

if choice.upper() == "C":
    c = float(input("Enter temperature in Celsius: "))
    f = (c * 9/5) + 32
    print("Temperature in Fahrenheit:", f)
elif choice.upper() == "F":
    f = float(input("Enter temperature in Fahrenheit: "))
    c = (f - 32) * 5/9
    print("Temperature in Celsius:", c)
else:
    print("Invalid choice")

a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
c = int(input("Enter third number: "))

if a >= b and a >= c:
    print("Largest:", a)
elif b >= a and b >= c:
    print("Largest:", b)
else:
    print("Largest:", c)

print("------ Weather Data Analyzer ------")

days = int(input("Enter the number of days: "))

temperatures = []

for i in range(days):
    temp = float(input(f"Enter temperature for Day {i+1}: "))
    temperatures.append(temp)

highest = max(temperatures)
lowest = min(temperatures)
average = sum(temperatures) / len(temperatures)

hot_days = 0
for temp in temperatures:
    if temp > 35:
        hot_days += 1

print("\n------ Report ------")
print("Highest Temperature :", highest, "°C")
print("Lowest Temperature  :", lowest, "°C")
print("Average Temperature :", round(average, 2), "°C")
print("Hot Days (>35°C)    :", hot_days)

print("===== Sales Report Generator =====")

sales = []

days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]

for day in days:
    amount = float(input(f"Enter sales for {day}: ₹"))
    sales.append(amount)

total_sales = sum(sales)
average_sales = total_sales / len(sales)
highest_sales = max(sales)
lowest_sales = min(sales)

best_day = days[sales.index(highest_sales)]
lowest_day = days[sales.index(lowest_sales)]

print("\n===== Weekly Sales Report =====")
print(f"Total Sales      : ₹{total_sales:.2f}")
print(f"Average Sales    : ₹{average_sales:.2f}")
print(f"Highest Sales    : ₹{highest_sales:.2f} ({best_day})")
print(f"Lowest Sales     : ₹{lowest_sales:.2f} ({lowest_day})")