# -*- coding: utf-8 -*-
"""week2 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YCqyUXvdOPZKRIwBNzWxNtSvBxrhlm5c
"""

numbers = [2, 4, 2, 5, 6, 4, 2, 7, 5]

frequency = {}

for num in numbers:
    if num in frequency:
        frequency[num] += 1
    else:
        frequency[num] = 1

print("Frequency of each element:")
for key, value in frequency.items():
    print(key, ":", value)

numbers = [45, 12, 78, 23, 9, 34]

ascending = sorted(numbers, key=lambda x: x)

descending = sorted(numbers, key=lambda x: x, reverse=True)

print("Original List:", numbers)
print("Ascending Order:", ascending)
print("Descending Order:", descending)

print("===== Student Data Cleaner =====")

students = []

n = int(input("Enter the number of student names: "))

for i in range(n):
    name = input(f"Enter name {i+1}: ")
    students.append(name)

# Remove duplicates
cleaned_students = list(set(students))

# Sort the list
cleaned_students.sort()

print("\n===== Cleaned Student List =====")
for student in cleaned_students:
    print(student)

search = input("\nEnter a student name to search: ")

if search in cleaned_students:
    print(search, "is present in the list.")
else:
    print(search, "is not present in the list.")