# -*- coding: utf-8 -*-
"""week4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13ZDWgGdlgGk_zkBDo0Y3Gcc7y3j0xAfj
"""

import matplotlib.pyplot as plt

months = ["Jan", "Feb", "Mar", "Apr", "May"]
sales = [1500, 1800, 1700, 2200, 2500]

plt.plot(months, sales, marker='o')
plt.title("Monthly Sales")
plt.xlabel("Months")
plt.ylabel("Sales")
plt.show()

import matplotlib.pyplot as plt

subjects = ["Math", "Science", "English", "Computer"]
marks = [85, 90, 78, 95]

plt.bar(subjects, marks)
plt.title("Student Marks")
plt.xlabel("Subjects")
plt.ylabel("Marks")
plt.show()

import matplotlib.pyplot as plt

marks = [45, 56, 67, 78, 89, 90, 76, 65, 88, 92]

plt.hist(marks, bins=5)
plt.title("Marks Distribution")
plt.xlabel("Marks")
plt.ylabel("Frequency")
plt.show()

import matplotlib.pyplot as plt

products = ["Laptop", "Mobile", "Tablet", "Accessories"]
sales = [35, 40, 15, 10]

plt.pie(sales, labels=products, autopct="%1.1f%%")
plt.title("Product Sales Distribution")
plt.show()

import matplotlib.pyplot as plt

hours = [1, 2, 3, 4, 5]
marks = [45, 55, 65, 80, 95]

plt.scatter(hours, marks)
plt.title("Study Hours vs Marks")
plt.xlabel("Study Hours")
plt.ylabel("Marks")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

data = [
    [85, 90, 88],
    [78, 82, 80],
    [92, 95, 91]
]

sns.heatmap(data, annot=True, cmap="Blues")

plt.title("Student Marks Heatmap")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

iris = sns.load_dataset("iris")

sns.pairplot(iris)

plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

tips = sns.load_dataset("tips")

sns.boxplot(x="day", y="total_bill", data=tips)

plt.title("Total Bill by Day")
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Sample Sales Data
data = {
    "Month": ["Jan", "Feb", "Mar", "Apr", "May", "Jun"],
    "Sales": [2500, 3200, 2800, 4000, 4500, 3800],
    "Profit": [500, 700, 600, 900, 1100, 850]
}

df = pd.DataFrame(data)

# Line Plot
plt.figure(figsize=(6,4))
plt.plot(df["Month"], df["Sales"], marker="o")
plt.title("Monthly Sales")
plt.xlabel("Month")
plt.ylabel("Sales")
plt.show()

# Bar Chart
plt.figure(figsize=(6,4))
plt.bar(df["Month"], df["Profit"])
plt.title("Monthly Profit")
plt.xlabel("Month")
plt.ylabel("Profit")
plt.show()

# Scatter Plot
plt.figure(figsize=(6,4))
plt.scatter(df["Sales"], df["Profit"])
plt.title("Sales vs Profit")
plt.xlabel("Sales")
plt.ylabel("Profit")
plt.show()

# Heatmap
plt.figure(figsize=(4,3))
sns.heatmap(df[["Sales", "Profit"]].corr(), annot=True, cmap="Blues")
plt.title("Correlation Heatmap")
plt.show()