# -*- coding: utf-8 -*-
"""week 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17E1raXqhk-NKTclLkwzOMrqP41JkrBot
"""

import numpy as np

a = np.array([10, 20, 30])
b = np.array([5, 10, 15])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

import pandas as pd

data = {
    "Name": ["Aman", "Priya", "Rahul"],
    "Age": [20, 21, 22],
    "Marks": [85, 90, 78]
}

df = pd.DataFrame(data)

print(df)

import pandas as pd

data = {
    "Name": ["Aman", "Priya", "Rahul", "Neha"],
    "Marks": [85, 90, 78, 88]
}

df = pd.DataFrame(data)

average = df["Marks"].mean()

print("Average Marks:", average)

import pandas as pd
import numpy as np

data = {
    "Name": ["Aman", "Priya", "Rahul", "Neha"],
    "Marks": [85, np.nan, 78, 88]
}

df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

df = df.dropna()

print("\nAfter Removing Missing Values:")
print(df)

import pandas as pd

data = {
    "Name": ["Aman", "Priya", "Rahul", "Neha"],
    "Class": ["A", "A", "B", "B"],
    "Marks": [85, 90, 78, 88]
}

df = pd.DataFrame(data)

result = df.groupby("Class")["Marks"].mean()

print(result)

import pandas as pd
import numpy as np

# Student data
data = {
    "Name": ["Aman", "Priya", "Rahul", "Neha", "Karan"],
    "Class": ["A", "A", "B", "B", "A"],
    "Marks": [85, np.nan, 78, 92, 88]
}

# Create DataFrame
df = pd.DataFrame(data)

print("Original Data:\n")
print(df)

# Remove missing values
df = df.dropna()

print("\nCleaned Data:\n")
print(df)

# Basic statistics
print("\nAverage Marks:", df["Marks"].mean())
print("Highest Marks:", df["Marks"].max())
print("Lowest Marks:", df["Marks"].min())

# Group by Class
print("\nAverage Marks by Class:")
print(df.groupby("Class")["Marks"].mean())